openapi: 3.0.0
info:
  title: 콘서트 예약 서비스 OPEN API
  version: 1.0.0
paths:
  /tokens:
    post:
      summary: 토큰 발급 API
      operationId: enrollToken
      parameters:
        - in: header
          name: X-USER-TOKEN
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenHttpRequest'
      responses:
        '200':
          description: 새로 발급되거나 초기화된 사용자 인증 토큰 반환
          headers:
            X-USER-TOKEN:
              schema:
                type: string
                format: uuid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenHttpResponse'

  /concerts/{concertId}/performance-date/{date}/queues:
    get:
      summary: 대기열 확인 API
      operationId: checkConcertDateQueueCount
      parameters:
        - in: header
          name: X-USER-TOKEN
          required: true
          schema:
            type: string
            format: uuid
        - in: path
          name: concertId
          required: true
          schema:
            type: integer
            format: int64
        - in: path
          name: date
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 대기열 남은 순서 반환
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueueCountHttpResponse'

  /concerts/{concertId}/reservations/available:
    get:
      summary: 예약 가능 날짜 조회 API
      operationId: selectAvailableConcertDates
      parameters:
        - in: header
          name: X-USER-TOKEN
          schema:
            type: string
            format: uuid
        - in: path
          name: concertId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 예약 가능한 날짜 목록 반환
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailableDatesHttpResponse'

  /concerts/{concertId}/performance-date/{date}/seats/available:
    get:
      summary: 예약 가능 좌석 조회 API
      operationId: selectAvailableConcertSeats
      parameters:
        - in: header
          name: X-USER-TOKEN
          schema:
            type: string
            format: uuid
        - in: path
          name: concertId
          required: true
          schema:
            type: integer
            format: int64
        - in: path
          name: date
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 예약 가능한 좌석 목록 반환
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AvailableSeatsHttpResponse'

  /concerts/{concertId}/performance-date/{date}/seats/{seatId}:
    post:
      summary: 좌석 예약 API
      operationId: reserveConcertSeat
      parameters:
        - in: header
          name: X-USER-TOKEN
          schema:
            type: string
            format: uuid
        - in: path
          name: concertId
          required: true
          schema:
            type: integer
            format: int64
        - in: path
          name: date
          required: true
          schema:
            type: string
            format: string
        - in: path
          name: seatId
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SeatReservationHttpRequest'
      responses:
        '200':
          description: 좌석 임시 배정 완료
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SeatReservationHttpResponse'

  /points:
    post:
      summary: 잔액 충전 API
      operationId: chargePoint
      parameters:
        - in: header
          name: X-USER-TOKEN
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PointChargeHttpRequest'
      responses:
        '200':
          description: 충전 완료 후 잔액 반환
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PointChargeHttpResponse'

    get:
      summary: 잔액 조회 API
      operationId: selectPoint
      parameters:
        - in: header
          name: X-USER-TOKEN
          schema:
            type: string
            format: uuid
        - in: query
          name: userId
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 현재 잔액 반환
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PointSelectHttpResponse'

  /order/payments:
    post:
      summary: 결제 API
      operationId: executePayment
      parameters:
        - in: header
          name: X-USER-TOKEN
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentHttpRequest'
      responses:
        '200':
          description: 결제 완료
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentHttpResponse'

components:
  schemas:
    TokenHttpRequest:
      type: object
      properties:
        userId:
          type: integer
          example: 1
          format: int64
    TokenHttpResponse:
      type: object
      properties:
        token:
          type: string
          example: "21113572-4cb4-44ef-8e19-63269724b8be"
          format: uuid

    QueueCountHttpResponse:
      type: object
      properties:
        count:
          type: integer
          example: 5

    AvailableDatesHttpResponse:
      type: array
      items:
        type: string
        example: "2024-10-20"

    AvailableSeatsHttpResponse:
      type: object
      properties:
        seatId:
          type: integer
          example: 3
          format: int64
        seatName:
          type: string
          example: "A-3"

    SeatReservationHttpRequest:
      type: object
      properties:
        userId:
          type: integer
          example: 1
          format: int64
    SeatReservationHttpResponse:
      type: object
      properties:
        message:
          type: string
          example: "좌석이 임시 배정되었습니다."

    PointChargeHttpRequest:
      type: object
      properties:
        userId:
          type: integer
          example: 1
          format: int64
        amount:
          type: integer
          example: 20000
    PointChargeHttpResponse:
      type: object
      properties:
        point:
          type: string
          example: 25000
          format: decimal

    PointSelectHttpResponse:
      type: object
      properties:
        point:
          type: string
          example: 25000
          format: decimal

    PaymentHttpRequest:
      type: object
      properties:
        userId:
          type: integer
          example: 1
          format: int64
        concertId:
          type: integer
          example: 1
          format: int64
        seatId:
          type: integer
          example: 1
          format: int64
        amount:
          type: integer
          example: 25000
    PaymentHttpResponse:
      type: object
      properties:
        message:
          type: string
          example: 결제가 완료되었습니다.
        paymentId:
          type: integer
          example: 1
          format: int64
