/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.schooldevops.apifirst.openapi.rest;

import com.schooldevops.apifirst.openapi.domain.AvailableSeatsResponseInner;
import java.util.Date;
import org.springframework.format.annotation.DateTimeFormat;
import com.schooldevops.apifirst.openapi.domain.QueueCountResponse;
import com.schooldevops.apifirst.openapi.domain.SeatReservationRequest;
import com.schooldevops.apifirst.openapi.domain.SeatReservationResponse;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-10-11T03:52:49.082651+09:00[Asia/Seoul]")
@Validated
@Tag(name = "concerts", description = "the concerts API")
public interface ConcertsApi {

    /**
     * GET /concerts/{concertId}/performance-date/{date}/queues : 대기열 확인 API
     *
     * @param X_USER_TOKEN  (required)
     * @param concertId  (required)
     * @param date  (required)
     * @return 대기열 남은 순서 반환 (status code 200)
     */
    @Operation(
        operationId = "checkConcertDateQueueCount",
        summary = "대기열 확인 API",
        responses = {
            @ApiResponse(responseCode = "200", description = "대기열 남은 순서 반환", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = QueueCountResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/concerts/{concertId}/performance-date/{date}/queues",
        produces = { "application/json" }
    )
    
    ResponseEntity<QueueCountResponse> checkConcertDateQueueCount(
        @NotNull @Parameter(name = "X-USER-TOKEN", description = "", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-USER-TOKEN", required = true) UUID X_USER_TOKEN,
        @Parameter(name = "concertId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("concertId") Integer concertId,
        @Parameter(name = "date", description = "", required = true, in = ParameterIn.PATH) @PathVariable("date") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) Date date
    );


    /**
     * POST /concerts/{concertId}/performance-date/{date}/seats/{seatId} : 좌석 예약 API
     *
     * @param concertId  (required)
     * @param date  (required)
     * @param seatId  (required)
     * @param X_USER_TOKEN  (optional)
     * @param seatReservationRequest  (optional)
     * @return 좌석 임시 배정 완료 (status code 200)
     */
    @Operation(
        operationId = "reserveConcertSeat",
        summary = "좌석 예약 API",
        responses = {
            @ApiResponse(responseCode = "200", description = "좌석 임시 배정 완료", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SeatReservationResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/concerts/{concertId}/performance-date/{date}/seats/{seatId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<SeatReservationResponse> reserveConcertSeat(
        @Parameter(name = "concertId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("concertId") Integer concertId,
        @Parameter(name = "date", description = "", required = true, in = ParameterIn.PATH) @PathVariable("date") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) Date date,
        @Parameter(name = "seatId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("seatId") Integer seatId,
        @Parameter(name = "X-USER-TOKEN", description = "", in = ParameterIn.HEADER) @RequestHeader(value = "X-USER-TOKEN", required = false) UUID X_USER_TOKEN,
        @Parameter(name = "SeatReservationRequest", description = "") @Valid @RequestBody(required = false) SeatReservationRequest seatReservationRequest
    );


    /**
     * GET /concerts/{concertId}/reservations/available : 예약 가능 날짜 조회 API
     *
     * @param concertId  (required)
     * @param X_USER_TOKEN  (optional)
     * @return 예약 가능한 날짜 목록 반환 (status code 200)
     */
    @Operation(
        operationId = "selectAvailableConcertDates",
        summary = "예약 가능 날짜 조회 API",
        responses = {
            @ApiResponse(responseCode = "200", description = "예약 가능한 날짜 목록 반환", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Date.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/concerts/{concertId}/reservations/available",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<Date>> selectAvailableConcertDates(
        @Parameter(name = "concertId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("concertId") Integer concertId,
        @Parameter(name = "X-USER-TOKEN", description = "", in = ParameterIn.HEADER) @RequestHeader(value = "X-USER-TOKEN", required = false) UUID X_USER_TOKEN
    );


    /**
     * GET /concerts/{concertId}/performance-date/{date}/seats/available : 예약 가능 좌석 조회 API
     *
     * @param concertId  (required)
     * @param date  (required)
     * @param X_USER_TOKEN  (optional)
     * @return 예약 가능한 좌석 목록 반환 (status code 200)
     */
    @Operation(
        operationId = "selectAvailableConcertSeats",
        summary = "예약 가능 좌석 조회 API",
        responses = {
            @ApiResponse(responseCode = "200", description = "예약 가능한 좌석 목록 반환", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = AvailableSeatsResponseInner.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/concerts/{concertId}/performance-date/{date}/seats/available",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<AvailableSeatsResponseInner>> selectAvailableConcertSeats(
        @Parameter(name = "concertId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("concertId") Integer concertId,
        @Parameter(name = "date", description = "", required = true, in = ParameterIn.PATH) @PathVariable("date") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) Date date,
        @Parameter(name = "X-USER-TOKEN", description = "", in = ParameterIn.HEADER) @RequestHeader(value = "X-USER-TOKEN", required = false) UUID X_USER_TOKEN
    );

}
