spring:
  application:
    name: hanghaeplus-concert-reservation-service

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:mysql://localhost:3306/concert_reservation
    username: yn3
    password: yn3!@#
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true

  mustache:
    check-template-location: false